version: "3.8"

services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8001:8001"
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8002:8002"
    depends_on:
      - product-service
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8003:8003"
    depends_on:
      - order-service
    restart: unless-stopped

